server:
  port: 8084

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userdb
    username: user
    password: userpassword
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect

logging:
  level:
    org.springframework: DEBUG
